export const GET_EXPENSES_START = 'GET_EXPENSES_START';
export const GET_EXPENSES_COMPLETE = 'GET_EXPENSES_COMPLETE';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const FIRE_MESSAGE = 'FIRE_MESSAGE';
